---
title: "pivot"
author: "oushiei"
date: '2022-06-01'
output:
  html_document:
    df_print: paged
  html_notebook:
    html_document: null
    theme: cerulean
    highlight: tango
---

```{css, echo=FALSE}
code {
    padding: 2px 4px;
    font-size: 90%;
    color: #c7254e;
    background-color: #f9f2f4;
    border-radius: 4px
}
```
knitr::opts_chunk$set(class.source = "watch-out")

```{r df-drop-ok, class.source=".code"}
mtcars[1:5, "mpg", drop = FALSE]
```


## 我想显示的代码

```{r class.source="code"}
library(dplyr)

#create data frame
df <- data.frame(player=c('A', 'B', 'C', 'D'),
                 year1=c(12, 15, 19, 19),
                 year2=c(22, 29, 18, 12));df
##整合col两列名,放到一列里,作为变量.
##值拿出来放到新列名的
library(tidyr)
df %>% pivot_longer(cols=c('year1', 'year2'),
                    names_to='year',
                    values_to='points')
##练习
iris%>% pivot_longer(cols=c('Petal.Length','Petal.Width'),
                     names_to=c('我起的'),
                     values_to=c('奇怪的名字'))

## pivot_wider() 
df
df %>% pivot_wider(names_from = player,values_from = year1)
  
```




<div class="footer">Copyright &copy;王子睿oushiei IN GuangXi Univisity</div>
