---
title: "选修本课程的个人陈述"
author: "oushiei"
date: '2022-06-08'
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 引言

本研究计划书基于R的[tinytex包](https://github.com/rstudio/tinytex)写成,同步于我的[个人博客](https://oushiei.netlify.app/),感谢老师观看!非常希望能够参加本次北京大学数字人文研究中心举办的数字人文工作坊,我会非常认真地对待本次培训!!

# 我的毕业论文

《Ｒによる翻訳文体研究》(中文译为:基于R与语料库的翻译文体研究)

### 论文的提出背景

\setlength{\parindent}{2em}

Baker[(1993)](https://www.taylorfrancis.com/chapters/edit/10.4324/9780429024221-2/corpus-linguistics-translation-studies-mona-baker)提了出的\underline{语料库翻译学}这一学科概念，使翻译学科从定性研究实现了定量研究的转变，而语料库翻译文体学是黄立波等教授基于语料库翻译学提出的新的研究范式:从"原作-译作"的双语研究模式创造性地拓宽了"译作-译作"模式的\underline{翻译文体研究}。 

日本方面因为受可供对比的译本数量、版权等种种原因，语料库翻译研究并未得到长足发展。但是基于文本挖掘、语料库的研究却非常兴盛，呈现\underline{强烈的跨学科性}与\underline{自然语言处理技术}紧密结合的趋势，这方面的研究具体来说有小说叙事构成研究[(赤石美奈，2006)](https://cir.nii.ac.jp/crid/1390282680082974080)，作家文体研究，如[(金明哲，2010)](https://www.cis.doshisha.ac.jp/staff/jin/)，[(工藤彰，2010)](https://cir.nii.ac.jp/crid/1390282679401094016)，舆情研究[(打田篤彦，2019)](https://cir.nii.ac.jp/crid/1390285697600187520)等等。 这些跨学科研究的范式，以及信息技术的应用是值得学习的，所以我的毕业论文就是将这些日本的文体学技术与国内的翻译文体学理论相结合，以《春琴抄》的五个译本为例子，基于R去将五个译者的文体以统计，可视化的方式去分析，尝试摆脱一些例如wordmith等集成软件的\underline{束缚}。

# 科研进展

-   毕业论文顺利进行小论文已经付梓待审;
-   同时进行一项基于R的翻译文体研究，目前撰写过半，数据已经较为详实;
-   与我校[刘君老师](https://fls.gxu.edu.cn/info/1064/2382.htm)在进行一项基于文本挖掘的《谷崎潤一郎の計量文体研究》

# 博士研究计划

-   继续深化对各种文本挖掘技术的学习，将其应用在数字人文研究中(包括但不限于翻译研究，文体研究)，通过R，Java等制作语料分析的集成软件。

-   主持，并获得一项翻译大赛的所有译本，建设一种免去人工评价译文的框架并制作集成软件。大幅度降低翻译大赛评委的主观性。实现一种翻译评价模式: 数据辅助译本筛选+人为干预评价。

# 总结

将日本的计量文体学的研究方法积极引入国内，应用到技术层面比较薄弱的人文学科是具有巨大潜力与价值的。
  
语料库语言学衍生了众多基于语料库的人文研究，这种跨学科性并不是从\underline{上到下兼容}的，应该是学科间\underline{相互借鉴、影响、活用}的过程.

笔者也会基于这一观点继续深入学习与研究。
  
  
  
  [返回引言处](#引言)