baseurl: https://oushiei.netlify.app/
languageCode: en-us
title: oushiei'website
theme: simpleness-main
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: AboutMe
      url: /author/关于我
    - name: Rの豆知識
      url: /Rの豆知識
    - name: Experience
      url: /experience
    - name: Publication
      url: https://kns.cnki.net/kcms/detail/knetsearch.aspx?dbcode=CJFD&code=000044219366&sfield=au&skey=%e7%8e%8b%e5%ad%90%e7%9d%bf&uniplatform=NZKPT
    
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: oushiei's academic blog.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: favicon.png
    height: 50
    url: favicon.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
